### ISSUE TITLE
Create common components, part 1

### ISSUE THREAD

**Issue by brettdh** [goinverse-oss/app#12]
## Implement Common Components, part 1

There are many common components used throughout the entire application design. We should create them upfront in order to promote reusability.

Some of these common components are very similar to each other. For example, the square tiles for Podcasts Series, Meditations Series, and Liturgies all look basically the same. I have grouped these components into single tasks. It will be up to the developer implementing these components if it makes sense to use a pattern (containment, for example).

### Scope:

For each of these, the focus should be on **presentation**; i.e.
- Don't worry about anything relating to Redux, or hooking these components up to the workflow of the app.
- For components that display some entity from the API, **do** structure the props based on the data model described in [our SwaggerHub project](https://app.swaggerhub.com/apis/The-Liturgists/the-liturgists-app/1.0).
  - Focus on the attributes and relationships rather than the exact structure. Assume that we will be using [a client library](http://jsonapi.org/implementations/#client-libraries-javascript) to deserialize the raw JSON:API structure to something nicer to work with in the app.
- Don't forget to reuse simpler components to build the more complicated ones.

### Tasks:

As you pick these up, please [create an issue](https://github.com/theliturgists/app/issues/new), assign yourself, and mention the issue next to its task in the list below.

Showcase
- [x] Add React-Native Storybook (#24)

Bits and bobs, could probably be done in one task (*brettdh: I decided to break 'em down anyway, since the code reviews will be unrelated*):
- [x] Implement circle pictures (#32)
- [x] Implement like and comment counters (#27)
- [x] Implement grey text pills (#35)

Full Components
- [x] Implement Tag List (#37)

Other stories previously here have been split to a new epic (#47).
