### ISSUE TITLE
Create common components, part 2

### ISSUE THREAD

**Issue by brettdh** [goinverse-oss/app#47]
## Implement Common Components, part 2

*split from #12*

There are many common components used throughout the entire application design. We should create them upfront in order to promote reusability.

Some of these common components are very similar to each other. For example, the square tiles for Podcasts Series, Meditations Series, and Liturgies all look basically the same. I have grouped these components into single tasks. It will be up to the developer implementing these components if it makes sense to use a pattern (containment, for example).

### Scope:

For each of these, the focus should be on **presentation**; i.e.
- Don't worry about anything relating to Redux, or hooking these components up to the workflow of the app.
- For components that display some entity from the API, **do** structure the props based on the data model described in [our SwaggerHub project](https://app.swaggerhub.com/apis/The-Liturgists/the-liturgists-app/1.0).
  - Focus on the attributes and relationships rather than the exact structure. Assume that we will be using [a client library](http://jsonapi.org/implementations/#client-libraries-javascript) to deserialize the raw JSON:API structure to something nicer to work with in the app.
- Don't forget to reuse simpler components to build the more complicated ones.

### Tasks:

As you pick these up, please [create an issue](https://github.com/theliturgists/app/issues/new), assign yourself, and mention the issue next to its task in the list below.

Full Components
- [x] Implement People Cards (#40)
- [x] Implement People List (#41)
- [x] Implement Series Tiles (#43)
  - [x] Podcasts Series (#44)
  - [x] Meditations Series
  - [x] Liturgies
- [x] Implement Playable Items (#49)
  - Liturgy track
  - Meditation track
  - Podcast track
- Implement Item List
  - *I **think** this is just a `ScrollView` on each `Screen` filled with the appropriate items. -bh*
- [x] Implement Event List card (#54)
- [x] Implement Track Info and Controls (#52)
  - (at the top of Liturgy, Meditation, and Podcast episode pages).
- [x] Implement Comments Section (#56)
