### ISSUE TITLE
Set up meditations state in Redux

### ISSUE THREAD

**Issue by brettdh** [goinverse-oss/app#76]
## Motivation
*Note: the mentions of "the first" below may or may not be true, depending on progress on #67. Revise description later if necessary.*

This will be the first non-trivial foray into populating the redux store with app state. It will be an opportunity to prove out and refine our Redux style guide.

We want to store all the state required to display all the screens from the [top-level Meditations screen] on down. However, we don't want to store more state than is needed, which comes up in this context because there are relations between resources. For instance, a meditation category has meditations, and meditations have contributors, but meditations and contributors are standalone entities that we will want to be able to look up outside the context of their related objects. The key is that our state design should allow this without creating duplication. This is referred to in the Redux docs as [*normalizing* the state shape], and the Meditations project is our first opportunity to try this out.

Chasing breadcrumbs from the redux docs: we should also consider using [redux-orm] to simplify some of the state management of this relational data. (See also the [redux-orm entry] in Mark Erikson's [Practical Redux] series.) If we decide not to (for instance, perhaps because it's overcomplicated and we're not sure if it will fit all use cases), we should definitely still consider using [ImmutableJS] to avoid accidental state mutation in reducers.

**Update: a couple of decisions**
- The SDK project will only deal with API requests, not state normalization
  - In particular, it will not use redux-orm - but the app still might
- The SDK project might still use *an* ORM, such as Coluquent or Sarala
  - Something just to make the json:api handling easier
  - **Update**: Coloquent and Sarala aren't ready for production.
  - Let's use [Kitsu] instead.
  - Matter of fact - Kitsu is so simple that I'm going to defer creating an SDK project at all until it's clearly needed.

## Plan of action
- [x] Decide on an initial approach and support libraries
  - Doesn't need to be a thorough evaluation; lean towards just trying out something that might work
  - **Decisions**:
    - ~~[Kitsu] for simplified JSON:API requests~~
      - Just kidding. Kitsu denormalizes the responses for convenience, making it unsuitable, since we want to normalize the state and handle responses generically by passing them to redux-orm models that match their type.
    - [redux-orm] for state normalization and memoized selectors
    - No SDK project just yet; extract later when it becomes clear what's reusable.
- [x] Make a fake API server for development purposes (#80)
- [x] Add actions, reducers, epics, and selectors for meditation state (#82)
  - Partially done; see #83
- [x] Add tests for all of the above (#82)
  - Partially done; see #83

## Scope
~API requests and associated epics (redux-observable) are not part of this story; just the synchronous actions, such as `fetchMeditation` or `fetchMeditationSuccess`, etc.~

Changed my mind. Let's make this complete, including API requests.

[Kitsu]: https://github.com/wopian/kitsu/tree/master/packages/kitsu
[top-level Meditations screen]: https://github.com/theliturgists/app/issues/75
[*normalizing* the state shape]: https://redux.js.org/recipes/structuring-reducers/normalizing-state-shape
[redux-orm]: https://github.com/tommikaikkonen/redux-orm
[ImmutableJS]: https://facebook.github.io/immutable-js/
[redux-orm entry]: http://blog.isquaredsoftware.com/2016/10/practical-redux-part-1-redux-orm-basics/#why-use-redux-orm
[Practical Redux]: http://blog.isquaredsoftware.com/2016/10/practical-redux-part-0-introduction/
